services:
  api:
    image: quarky-api:latest
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8080:8080
    restart: unless-stopped
  ui:
    image: quarky-ui:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 4200:8080
    restart: unless-stopped
